version: '3.9'
services:
  api:
    build: .
    image: plx-hono-api:latest
    container_name: plx-hono-api
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped
    # If you want local logs mounted, uncomment:
    volumes:
      - ./logs:/app/logs
