/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/WeatherForecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetWeatherForecast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/{tenantId}/gateway": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    ssid?: string;
                };
                header?: never;
                path: {
                    tenantId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GatewayConfigResponse"];
                        "application/json": components["schemas"]["GatewayConfigResponse"];
                        "text/json": components["schemas"]["GatewayConfigResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/{tenantId}/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PortalSiteResponse"][];
                        "application/json": components["schemas"]["PortalSiteResponse"][];
                        "text/json": components["schemas"]["PortalSiteResponse"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/{tenantId}/branding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    ssid?: string;
                };
                header?: never;
                path: {
                    tenantId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PortalBrandingResponse"];
                        "application/json": components["schemas"]["PortalBrandingResponse"];
                        "text/json": components["schemas"]["PortalBrandingResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sites/{siteId}/ads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    siteId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    siteId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateAdsConfigRequest"];
                    "text/json": components["schemas"]["UpdateAdsConfigRequest"];
                    "application/*+json": components["schemas"]["UpdateAdsConfigRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sites/{siteId}/branding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    siteId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    siteId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateBrandingRequest"];
                    "text/json": components["schemas"]["UpdateBrandingRequest"];
                    "application/*+json": components["schemas"]["UpdateBrandingRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sites/{siteId}/branding/colors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    siteId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateColorsRequest"];
                    "text/json": components["schemas"]["UpdateColorsRequest"];
                    "application/*+json": components["schemas"]["UpdateColorsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sites/{siteId}/branding/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    siteId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateImagesRequest"];
                    "text/json": components["schemas"]["UpdateImagesRequest"];
                    "application/*+json": components["schemas"]["UpdateImagesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sites/{siteId}/branding/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    siteId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateContentRequest"];
                    "text/json": components["schemas"]["UpdateContentRequest"];
                    "application/*+json": components["schemas"]["UpdateContentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sites/{siteId}/branding/images/{imageType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    siteId: string;
                    imageType: components["schemas"]["BrandingImageType"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{siteId}/branding/images/{imageType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    siteId: string;
                    imageType: components["schemas"]["BrandingImageType"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sites/{siteId}/radius": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    siteId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RadiusConfigResponse"];
                        "application/json": components["schemas"]["RadiusConfigResponse"];
                        "text/json": components["schemas"]["RadiusConfigResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    siteId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateRadiusConfigRequest"];
                    "text/json": components["schemas"]["UpdateRadiusConfigRequest"];
                    "application/*+json": components["schemas"]["UpdateRadiusConfigRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RadiusConfigResponse"];
                        "application/json": components["schemas"]["RadiusConfigResponse"];
                        "text/json": components["schemas"]["RadiusConfigResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tenants/{tenantId}/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSiteRequest"];
                    "text/json": components["schemas"]["CreateSiteRequest"];
                    "application/*+json": components["schemas"]["CreateSiteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sites/{siteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    siteId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    siteId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateSiteRequest"];
                    "text/json": components["schemas"]["UpdateSiteRequest"];
                    "application/*+json": components["schemas"]["UpdateSiteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    siteId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sites/{siteId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    siteId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateSiteStatusRequest"];
                    "text/json": components["schemas"]["UpdateSiteStatusRequest"];
                    "application/*+json": components["schemas"]["UpdateSiteStatusRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTenantRequest"];
                    "text/json": components["schemas"]["CreateTenantRequest"];
                    "application/*+json": components["schemas"]["CreateTenantRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tenants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTenantRequest"];
                    "text/json": components["schemas"]["UpdateTenantRequest"];
                    "application/*+json": components["schemas"]["UpdateTenantRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BrandingImageType: number;
        CreateSiteRequest: {
            ssid?: string;
            name?: string;
            domain?: null | string;
            /** Format: int32 */
            sortOrder?: number | string;
        };
        CreateTenantRequest: {
            name?: string;
            slug?: string;
        };
        GatewayConfigResponse: {
            loginUrl?: null | string;
            freeUsername?: null | string;
            freePassword?: null | string;
        };
        /** Format: binary */
        IFormFile: string;
        PortalBrandingResponse: {
            ssid?: string;
            displayName?: null | string;
            brandPrimary?: string;
            brandPrimaryHover?: string;
            brandSecondary?: string;
            brandAccent?: string;
            textPrimary?: string;
            textSecondary?: string;
            textTertiary?: string;
            textMuted?: string;
            surfaceCard?: string;
            surfaceWhite?: string;
            surfaceBorder?: string;
            buttonPrimary?: string;
            buttonPrimaryHover?: string;
            buttonPrimaryText?: string;
            buttonSecondary?: string;
            buttonSecondaryHover?: string;
            buttonSecondaryText?: string;
            logoUrl?: string;
            logoWhiteUrl?: string;
            connectCardBgUrl?: string;
            bannerOverlayUrl?: null | string;
            faviconUrl?: null | string;
            splashBgUrl?: null | string;
            heading?: null | string;
            subheading?: null | string;
            splashHeading?: null | string;
            buttonText?: null | string;
            termsLinks?: null | string;
            venueLabel?: null | string;
            venueRoute?: null | string;
            /** Format: int32 */
            sortOrder?: number | string;
            authMethods?: string[];
            marketingOptIn?: boolean;
            adsEnabled?: boolean;
            adsReviveServerUrl?: null | string;
            adsReviveZoneId?: null | string;
            adsReviveId?: null | string;
            adsVastUrl?: null | string;
        };
        PortalSiteResponse: {
            ssid?: string;
            displayName?: null | string;
            logoUrl?: string;
            /** Format: int32 */
            sortOrder?: number | string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        RadiusConfigResponse: {
            siteId?: string;
            gatewayUrl?: null | string;
            freeUsername?: null | string;
            freePassword?: null | string;
            radiusDeskUrl?: null | string;
            radiusDeskApiToken?: null | string;
            radiusDeskRealmId?: null | string;
            radiusDeskCloudId?: null | string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        SiteStatus: number;
        UpdateAdsConfigRequest: {
            reviveServerUrl?: null | string;
            reviveZoneId?: null | string;
            reviveId?: null | string;
            vastUrl?: null | string;
            isEnabled?: null | boolean;
        };
        UpdateBrandingRequest: {
            brandPrimary?: null | string;
            brandPrimaryHover?: null | string;
            brandSecondary?: null | string;
            brandAccent?: null | string;
            textPrimary?: null | string;
            textSecondary?: null | string;
            textTertiary?: null | string;
            textMuted?: null | string;
            surfaceCard?: null | string;
            surfaceWhite?: null | string;
            surfaceBorder?: null | string;
            buttonPrimary?: null | string;
            buttonPrimaryHover?: null | string;
            buttonPrimaryText?: null | string;
            buttonSecondary?: null | string;
            buttonSecondaryHover?: null | string;
            buttonSecondaryText?: null | string;
            logoUrl?: null | string;
            logoWhiteUrl?: null | string;
            connectCardBgUrl?: null | string;
            bannerOverlayUrl?: null | string;
            faviconUrl?: null | string;
            splashBgUrl?: null | string;
            displayName?: null | string;
            heading?: null | string;
            subheading?: null | string;
            splashHeading?: null | string;
            buttonText?: null | string;
            termsLinks?: null | string;
            venueLabel?: null | string;
            venueRoute?: null | string;
            /** Format: int32 */
            sortOrder?: null | number | string;
        };
        UpdateColorsRequest: {
            brandPrimary?: null | string;
            brandPrimaryHover?: null | string;
            brandSecondary?: null | string;
            brandAccent?: null | string;
            textPrimary?: null | string;
            textSecondary?: null | string;
            textTertiary?: null | string;
            textMuted?: null | string;
            surfaceCard?: null | string;
            surfaceWhite?: null | string;
            surfaceBorder?: null | string;
            buttonPrimary?: null | string;
            buttonPrimaryHover?: null | string;
            buttonPrimaryText?: null | string;
            buttonSecondary?: null | string;
            buttonSecondaryHover?: null | string;
            buttonSecondaryText?: null | string;
        };
        UpdateContentRequest: {
            displayName?: null | string;
            heading?: null | string;
            subheading?: null | string;
            splashHeading?: null | string;
            buttonText?: null | string;
            termsLinks?: null | string;
            venueLabel?: null | string;
            venueRoute?: null | string;
            /** Format: int32 */
            sortOrder?: null | number | string;
        };
        UpdateImagesRequest: {
            logoUrl?: null | string;
            logoWhiteUrl?: null | string;
            connectCardBgUrl?: null | string;
            bannerOverlayUrl?: null | string;
            faviconUrl?: null | string;
            splashBgUrl?: null | string;
        };
        UpdateRadiusConfigRequest: {
            gatewayUrl?: null | string;
            freeUsername?: null | string;
            freePassword?: null | string;
            radiusDeskUrl?: null | string;
            radiusDeskApiToken?: null | string;
            radiusDeskRealmId?: null | string;
            radiusDeskCloudId?: null | string;
        };
        UpdateSiteRequest: {
            ssid?: string;
            name?: string;
            domain?: null | string;
            /** Format: int32 */
            sortOrder?: number | string;
            authMethods?: null | string[];
            marketingOptIn?: null | boolean;
        };
        UpdateSiteStatusRequest: {
            status?: components["schemas"]["SiteStatus"];
        };
        UpdateTenantRequest: {
            name?: string;
            slug?: string;
        };
        WeatherForecast: {
            /** Format: date */
            date?: string;
            /** Format: int32 */
            temperatureC?: number | string;
            /** Format: int32 */
            temperatureF?: number | string;
            summary?: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetWeatherForecast: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["WeatherForecast"][];
                    "application/json": components["schemas"]["WeatherForecast"][];
                    "text/json": components["schemas"]["WeatherForecast"][];
                };
            };
        };
    };
}
