import type { BrandingConfig } from '@/lib/types/branding.types'

export const mockBranding: BrandingConfig[] = [
  {
    id: 'brand_joburg_main',
    siteId: 'site_joburg_main',
    primaryColor: '#c8a96e',
    secondaryColor: '#1a1a2e',
    accentColor: '#e8c547',
    backgroundColor: '#0d0d1a',
    surfaceColor: '#1a1a2e',
    textPrimaryColor: '#f5f0e8',
    textSecondaryColor: '#a89070',
    buttonTextColor: '#0d0d1a',
    buttonHoverColor: '#b8994e',
    linkColor: '#c8a96e',
    borderColor: '#2a2a3e',
    errorColor: '#ef4444',
    successColor: '#22c55e',
    warningColor: '#f59e0b',
    headerBgColor: '#0d0d1a',
    footerBgColor: '#0d0d1a',
    inputBgColor: '#1a1a2e',
    logoUrl: 'https://placehold.co/200x60/c8a96e/0d0d1a?text=Joburg+Theatre',
    backgroundImageUrl: '',
    faviconUrl: '',
    headingText: 'Welcome to Joburg Theatre',
    subheadingText: 'Stay connected during your performance experience',
    connectButtonText: 'Connect to WiFi',
    termsText: 'By connecting, you agree to our Terms & Conditions',
    termsUrl: '/terms',
    privacyUrl: '/privacy',
    footerText: 'Powered by AuraConnect',
    venueLabel: 'Joburg Theatre',
    venueRoute: '/joburg-theatre',
    updatedAt: '2024-12-01T10:00:00Z',
  },
  {
    id: 'brand_joburg_cafe',
    siteId: 'site_joburg_cafe',
    primaryColor: '#c8a96e',
    secondaryColor: '#1a1a2e',
    accentColor: '#e8c547',
    backgroundColor: '#0d0d1a',
    surfaceColor: '#1a1a2e',
    textPrimaryColor: '#f5f0e8',
    textSecondaryColor: '#a89070',
    buttonTextColor: '#0d0d1a',
    buttonHoverColor: '#b8994e',
    linkColor: '#c8a96e',
    borderColor: '#2a2a3e',
    errorColor: '#ef4444',
    successColor: '#22c55e',
    warningColor: '#f59e0b',
    headerBgColor: '#0d0d1a',
    footerBgColor: '#0d0d1a',
    inputBgColor: '#1a1a2e',
    logoUrl: 'https://placehold.co/200x60/c8a96e/0d0d1a?text=JT+Cafe',
    backgroundImageUrl: '',
    faviconUrl: '',
    headingText: 'Welcome to Joburg Theatre Café',
    subheadingText: 'Enjoy complimentary WiFi while you dine',
    connectButtonText: 'Connect Now',
    termsText: 'By connecting, you agree to our Terms & Conditions',
    termsUrl: '/terms',
    privacyUrl: '/privacy',
    footerText: 'Powered by AuraConnect',
    venueLabel: 'Joburg Theatre Café',
    venueRoute: '/joburg-theatre',
    updatedAt: '2024-11-15T09:30:00Z',
  },
  {
    id: 'brand_kwa_beach',
    siteId: 'site_kwa_beach',
    primaryColor: '#0ea5e9',
    secondaryColor: '#0f4c75',
    accentColor: '#fbbf24',
    backgroundColor: '#0c1929',
    surfaceColor: '#0f4c75',
    textPrimaryColor: '#f0f9ff',
    textSecondaryColor: '#7dd3fc',
    buttonTextColor: '#0c1929',
    buttonHoverColor: '#38bdf8',
    linkColor: '#7dd3fc',
    borderColor: '#1e3a5f',
    errorColor: '#ef4444',
    successColor: '#22c55e',
    warningColor: '#fbbf24',
    headerBgColor: '#0c1929',
    footerBgColor: '#0c1929',
    inputBgColor: '#0f4c75',
    logoUrl: 'https://placehold.co/200x60/0ea5e9/0c1929?text=Kwamaimai+Beach',
    backgroundImageUrl: '',
    faviconUrl: '',
    headingText: 'Welcome to Kwamaimai Beach',
    subheadingText: 'Relax and stay connected by the sea',
    connectButtonText: 'Get Connected',
    termsText: 'By connecting, you agree to our Terms & Conditions',
    termsUrl: '/terms',
    privacyUrl: '/privacy',
    footerText: 'Powered by AuraConnect',
    venueLabel: 'Kwamaimai Beach',
    venueRoute: '/kwamaimai-beach',
    updatedAt: '2024-12-05T11:00:00Z',
  },
]

export function getMockBrandingBySiteId(siteId: string): BrandingConfig | undefined {
  return mockBranding.find((b) => b.siteId === siteId)
}
