import type { Package } from '@/lib/types/package.types'

export const mockPackages: Package[] = [
  // Joburg Theatre - Main Hall
  {
    id: 'pkg_joburg_main_free',
    siteId: 'site_joburg_main',
    name: 'Complimentary Access',
    description: 'Free WiFi for all theatre guests',
    price: 0,
    currency: 'ZAR',
    durationValue: 3,
    durationType: 'hours',
    dataLimitMb: 200,
    downloadSpeedKbps: 2048,
    uploadSpeedKbps: 512,
    radiusProfile: 'free-basic',
    active: true,
    sortOrder: 1,
    createdAt: '2024-01-20T08:00:00Z',
    updatedAt: '2024-11-01T10:00:00Z',
  },
  {
    id: 'pkg_joburg_main_premium',
    siteId: 'site_joburg_main',
    name: 'Premium 24hr',
    description: 'Unlimited high-speed access for 24 hours',
    price: 49,
    currency: 'ZAR',
    durationValue: 24,
    durationType: 'hours',
    dataLimitMb: undefined,
    downloadSpeedKbps: 10240,
    uploadSpeedKbps: 5120,
    radiusProfile: 'premium-24hr',
    active: true,
    sortOrder: 2,
    createdAt: '2024-01-20T08:00:00Z',
    updatedAt: '2024-11-01T10:00:00Z',
  },

  // Kwamaimai Beach
  {
    id: 'pkg_kwa_beach_1hr',
    siteId: 'site_kwa_beach',
    name: '1 Hour Surf',
    description: 'Perfect for a quick beach session',
    price: 15,
    currency: 'ZAR',
    durationValue: 1,
    durationType: 'hours',
    dataLimitMb: 500,
    downloadSpeedKbps: 4096,
    uploadSpeedKbps: 1024,
    radiusProfile: 'beach-1hr',
    active: true,
    sortOrder: 1,
    createdAt: '2024-02-15T09:00:00Z',
    updatedAt: '2024-11-15T12:00:00Z',
  },
  {
    id: 'pkg_kwa_beach_day',
    siteId: 'site_kwa_beach',
    name: 'Full Day Pass',
    description: 'Unlimited access for the whole day',
    price: 69,
    currency: 'ZAR',
    durationValue: 24,
    durationType: 'hours',
    dataLimitMb: undefined,
    downloadSpeedKbps: 8192,
    uploadSpeedKbps: 2048,
    radiusProfile: 'beach-daypass',
    active: true,
    sortOrder: 2,
    createdAt: '2024-02-15T09:00:00Z',
    updatedAt: '2024-11-15T12:00:00Z',
  },
  {
    id: 'pkg_kwa_beach_free',
    siteId: 'site_kwa_beach',
    name: 'Social Media (Free)',
    description: 'Free access to social media platforms only',
    price: 0,
    currency: 'ZAR',
    durationValue: 30,
    durationType: 'minutes',
    dataLimitMb: 100,
    downloadSpeedKbps: 1024,
    uploadSpeedKbps: 256,
    radiusProfile: 'social-free',
    active: true,
    sortOrder: 3,
    createdAt: '2024-03-01T09:00:00Z',
    updatedAt: '2024-11-15T12:00:00Z',
  },

  // Sandton City - Level 1
  {
    id: 'pkg_sandton_l1_30min',
    siteId: 'site_sandton_l1',
    name: '30 Min Shopper',
    description: 'Quick browsing while you shop',
    price: 0,
    currency: 'ZAR',
    durationValue: 30,
    durationType: 'minutes',
    dataLimitMb: 150,
    downloadSpeedKbps: 2048,
    uploadSpeedKbps: 512,
    radiusProfile: 'shopper-free',
    active: true,
    sortOrder: 1,
    createdAt: '2024-03-10T07:30:00Z',
    updatedAt: '2024-12-01T09:00:00Z',
  },
  {
    id: 'pkg_sandton_l1_premium',
    siteId: 'site_sandton_l1',
    name: 'Premium Shopper',
    description: 'High-speed access for 4 hours',
    price: 39,
    currency: 'ZAR',
    durationValue: 4,
    durationType: 'hours',
    dataLimitMb: undefined,
    downloadSpeedKbps: 20480,
    uploadSpeedKbps: 10240,
    radiusProfile: 'shopper-premium',
    active: true,
    sortOrder: 2,
    createdAt: '2024-03-10T07:30:00Z',
    updatedAt: '2024-12-01T09:00:00Z',
  },
]
