import type { AdminUser } from '@/lib/types/user.types'

export const mockUsers: AdminUser[] = [
  {
    id: 'user_super_001',
    // email: 'super@auraconnect.com',
    email: 'charles@mbvit.co.za',
    firstName: 'Charles',
    lastName: 'Charles',
    role: 'super_admin',
    tenantIds: [],
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
    lastSignInAt: '2024-12-12T08:30:00Z',
  },
  {
    id: 'user_joburg_001',
    email: 'admin@joburg-theatre.co.za',
    firstName: 'Sipho',
    lastName: 'Nkosi',
    role: 'admin',
    tenantIds: ['tenant_joburg'],
    status: 'active',
    createdAt: '2024-01-16T09:00:00Z',
    lastSignInAt: '2024-12-11T07:45:00Z',
  },
  {
    id: 'user_kwa_001',
    email: 'admin@kwamaimai.co.za',
    firstName: 'Zanele',
    lastName: 'Dlamini',
    role: 'admin',
    tenantIds: ['tenant_kwamaimai'],
    status: 'active',
    createdAt: '2024-02-12T10:00:00Z',
    lastSignInAt: '2024-12-10T11:20:00Z',
  },
  {
    id: 'user_sandton_001',
    email: 'tech@sandtoncity.com',
    firstName: 'Lerato',
    lastName: 'Mokoena',
    role: 'admin',
    tenantIds: ['tenant_sandton'],
    status: 'active',
    createdAt: '2024-03-06T08:00:00Z',
    lastSignInAt: '2024-12-09T14:30:00Z',
  },
  {
    id: 'user_multi_001',
    email: 'regional@auraconnect.com',
    firstName: 'Thabo',
    lastName: 'Khumalo',
    role: 'admin',
    tenantIds: ['tenant_joburg', 'tenant_kwamaimai'],
    status: 'active',
    createdAt: '2024-05-01T09:00:00Z',
    lastSignInAt: '2024-12-08T16:00:00Z',
  },
  {
    id: 'user_pending_001',
    email: 'new.admin@example.com',
    firstName: 'Ayanda',
    lastName: 'Mahlangu',
    role: 'admin',
    tenantIds: ['tenant_pta_zoo'],
    status: 'pending',
    createdAt: '2024-12-10T10:00:00Z',
  },
]
