
services:
  cityofjbh-portal:
    build:
      context: .
      dockerfile: Dockerfile
    image: captive-portal:cityofjbh
    container_name: captive-portal-cityofjbh
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
      # Development/Test Settings
      - USE_SEED_DATA=${USE_SEED_DATA:-false}
      
      # Site Metadata
      - SITE_TITLE=${SITE_TITLE:-Jozi Free Wifi}
      - SITE_DESCRIPTION=${SITE_DESCRIPTION:-City of Johannesburg Free WiFi}
      - BRAND_NAME=${BRAND_NAME:-Jozi Free Wifi}
      
      # Navigation and Links
      - LOGO_CLICK_URL=${LOGO_CLICK_URL:-https://joburg.org.za}
      - HOME_URL=${HOME_URL:-/}
      - VIEW_ALL_NEWS_URL=${VIEW_ALL_NEWS_URL:-#}
      
      # Hotspot Configuration
      - HOTSPOT_PROVIDER_NAME=${HOTSPOT_PROVIDER_NAME:-City of Johannesburg}
      - HOTSPOT_FREE_DATA_AMOUNT=${HOTSPOT_FREE_DATA_AMOUNT:-2 GB}
      - HOTSPOT_WELCOME_MESSAGE=${HOTSPOT_WELCOME_MESSAGE:-Get 2 GB of internet free of cost, provided by City of Johannesburg}
      - HOTSPOT_SSID=${HOTSPOT_SSID:-JoziFreeWifi}
      
      # Mikrotik Credentials and Settings
      - MIKROTIK_DEFAULT_USERNAME=${MIKROTIK_DEFAULT_USERNAME:-click_to_connect@coj}
      - MIKROTIK_DEFAULT_PASSWORD=${MIKROTIK_DEFAULT_PASSWORD:-click_to_connect}
      - MIKROTIK_RADIUS_DESK_BASE_URL=${MIKROTIK_RADIUS_DESK_BASE_URL:-https://radiusdesk.joburg.org.za}
      - MIKROTIK_REDIRECT_URL=${MIKROTIK_REDIRECT_URL:-https://joburg.org.za}
      
      # Revive Ad Configuration
      - ADS_REVIVE_SERVER_URL=${ADS_REVIVE_SERVER_URL:-//servedby.revive-adserver.net/asyncjs.php}
      - ADS_ZONE_ID=${ADS_ZONE_ID:-20641}
      - ADS_REVIVE_ID=${ADS_REVIVE_ID:-727bec5e09208690b050ccfc6a45d384}
      
      # UI Messages
      - MESSAGE_LOADING_CONNECT=${MESSAGE_LOADING_CONNECT:-Connecting to Jozi Free WiFi...}
      - MESSAGE_SUCCESS_CONNECT=${MESSAGE_SUCCESS_CONNECT:-Successfully connected to Jozi Free WiFi!}
      - MESSAGE_ERROR_CONNECT=${MESSAGE_ERROR_CONNECT:-Failed to connect. Please try again.}
      - MESSAGE_CURRENT_PLAN_TITLE=${MESSAGE_CURRENT_PLAN_TITLE:-Hotspot usage}
      - MESSAGE_OUT_OF_INTERNET=${MESSAGE_OUT_OF_INTERNET:-You're out of internet!}
      - MESSAGE_VOUCHER_PLACEHOLDER=${MESSAGE_VOUCHER_PLACEHOLDER:-Enter voucher code}
      
      # Theme Selection
      - SELECTED_THEME=${SELECTED_THEME:-cityofjbh}
    env_file:
      - .env.cityofjbh
    restart: unless-stopped
    networks:
      - default
      - public-proxy

networks:
  default:
    name: next-captive-portal
  public-proxy:
    external: true