version: '3.8'

services:
  hotspot-app:
    container_name: hotspot-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      # Ensure container listens on 3001 by default; override with PORT env or .env file
      - PORT=${PORT:-3001}
      # Ensure container listens on 3001 by default; override with PORT env or .env file
      - NEXT_PUBLIC_SSID=${NEXT_PUBLIC_SSID:-Jozi-wifi}
      # Optionally expose NODE_ENV, defaults to production in Dockerfile
      - NODE_ENV=${NODE_ENV:-production}
    ports:
      - "${HOST_PORT:-3001}:${PORT:-3001}"
    restart: unless-stopped
    networks:
      - default
      - public-proxy

networks:
  default:
    name: hotspot-app-default
  public-proxy:
    external: true
