services:
  # PluxNet Configuration
  pluxnet-portal:
    build:
      context: .
      dockerfile: Dockerfile
    image: captive-portal:pluxnet
    container_name: captive-portal-pluxnet
    ports:
      - "3000:3000"
    env_file:
      - .env.pluxnet
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
    restart: unless-stopped
    networks:
      - default
      - public-proxy

networks:
  default:
    name: next-captive-portal
  public-proxy:
    external: true
