services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      # If you later need build-time args, you can pass them here; currently we COPY .env during build.
      # args:
      #   - NEXT_PUBLIC_BASE_URL
    image: vv-hotspot:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      # Ensure production mode in container
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    depends_on:
      # Uncomment if you run Postgres here
      # - db
      []
    restart: unless-stopped
  # Example Postgres service if you want it here (optional)
  # db:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_PASSWORD: example
  #   volumes:
  #     - dbdata:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  # volumes:
  #   dbdata:
