version: "3.9"

services:
  next-captive-portal:
    build:
      context: .
      dockerfile: Dockerfile
    image: next-captive-portal
    container_name: next-captive-portal
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
      # Uncomment to disable Next.js telemetry
      # - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - default
      - public-proxy

networks:
  default:
    name: next-captive-portal
  public-proxy:
    external: true