// New flat branding config exports using generated API type

import { BrandingConfig } from "./types";

// export const pluxnetTheme: BrandingConfig = {
//   id: 0,
//   ssid: 'default',
//   name: 'PluxNet',
//   heading: 'Connect to the Internet',
//   subheading: 'Fast. Reliable. Secure.',
//   buttonText: 'Connect Now',
//   termsLinks: 'https://pluxnet.co.za/terms',
//   brandPrimary: '#301358',
//   brandPrimaryHover: '#5B3393',
//   brandSecondary: '#F2F2F2',
//   brandAccent: '#F60031',
//   textPrimary: '#181818',
//   textSecondary: '#5D5D5D',
//   textTertiary: '#7A7A7A',
//   textMuted: '#CECECE',
//   surfaceCard: '#F2F2F2',
//   surfaceWhite: '#FFFFFF',
//   surfaceBorder: '#CECECE',
//   buttonPrimary: '#301358',
//   buttonPrimaryHover: '#5B3393',
//   buttonPrimaryText: '#FFFFFF',
//   buttonSecondary: '#FFFFFF',
//   buttonSecondaryHover: '#f5f5f5',
//   buttonSecondaryText: '#301358',
//   logo: '/pluxnet-logo.svg',
//   logoWhite: '/pluxnet-logo-white.svg',
//   connectCardBackground: '/internet-claim-bg.png',
//   bannerOverlay: '/banner-overlay.png',
//   favicon: '/favicon.svg',
//   createdAt: new Date(0).toISOString(),
//   updatedAt: new Date(0).toISOString()
// };

export const pluxnetTheme: BrandingConfig = {
  id: 4,
  ssid: "pluxnet-fibre",
  name: "PluxNet Fibre Hotspot",
  brandPrimary: "#301358",
  brandPrimaryHover: "#5B3393",
  brandSecondary: "#F2F2F2",
  brandAccent: "#F60031",
  textPrimary: "#181818",
  textSecondary: "#5D5D5D",
  textTertiary: "#7A7A7A",
  textMuted: "#CECECE",
  surfaceCard: "#F2F2F2",
  surfaceWhite: "#FFFFFF",
  surfaceBorder: "#CECECE",
  buttonPrimary: "#301358",
  buttonPrimaryHover: "#5B3393",
  buttonPrimaryText: "#FFFFFF",
  buttonSecondary: "#FFFFFF",
  buttonSecondaryHover: "#f5f5f5",
  buttonSecondaryText: "#301358",
  logo: "/pluxnet-fibre/logo",
  logoWhite: "/pluxnet-logo-white.svg",
  connectCardBackground: "/internet-claim-bg.png",
  bannerOverlay: null,
  favicon: "/favicon.svg",
  adsReviveServerUrl: "//servedby.revive-adserver.net/asyncjs.php",
  adsZoneId: "20641",
  adsReviveId: "727bec5e09208690b050ccfc6a45d384",
  adsVastUrl: "https://servedby.revive-adserver.net/fc.php?script=apVideo:vast2&zoneid=24615",
  termsLinks: "https://pluxnet.co.za/terms-conditions/",
  heading: "Welcome to PluxNet Public Wifi",
  subheading: null,
  buttonText: null,
  createdAt: new Date(0).toISOString(),
  updatedAt: new Date(0).toISOString()
}

export const exampleBusinessTheme: BrandingConfig = {
  id: 0,
  ssid: 'example-venue',
  name: 'Example Business',
  heading: 'Welcome!',
  subheading: 'Enjoy complimentary Wi‑Fi',
  buttonText: 'Get Online',
  termsLinks: 'https://example.com/terms',
  brandPrimary: '#2563eb',
  brandPrimaryHover: '#1d4ed8',
  brandSecondary: '#f8fafc',
  brandAccent: '#dc2626',
  textPrimary: '#1e293b',
  textSecondary: '#64748b',
  textTertiary: '#94a3b8',
  textMuted: '#cbd5e1',
  surfaceCard: '#f8fafc',
  surfaceWhite: '#ffffff',
  surfaceBorder: '#cbd5e1',
  buttonPrimary: '#2563eb',
  buttonPrimaryHover: '#1d4ed8',
  buttonPrimaryText: '#ffffff',
  buttonSecondary: '#ffffff',
  buttonSecondaryHover: '#f1f5f9',
  buttonSecondaryText: '#2563eb',
  logo: '/pluxnet-logo.svg',
  logoWhite: '/pluxnet-logo-white.svg',
  connectCardBackground: '/internet-claim-bg.png',
  bannerOverlay: '/banner-overlay.png',
  favicon: '/favicon.svg',
  createdAt: new Date(0).toISOString(),
  updatedAt: new Date(0).toISOString()
};

export const CityOfJbhTheme: BrandingConfig = {
  id: 0,
  ssid: 'jozi-free-wifi',
  name: 'Jozi Free Wifi',
  heading: 'Jozi Free Wi‑Fi',
  subheading: 'Connecting the City',
  buttonText: 'Claim Access',
  termsLinks: 'https://joburg.org/terms',
  brandPrimary: '#FFB600',
  brandPrimaryHover: '#E6A500',
  brandSecondary: '#F2F2F2',
  brandAccent: '#F60031',
  textPrimary: '#181818',
  textSecondary: '#5D5D5D',
  textTertiary: '#7A7A7A',
  textMuted: '#CECECE',
  surfaceCard: '#F2F2F2',
  surfaceWhite: '#FFFFFF',
  surfaceBorder: '#CECECE',
  buttonPrimary: '#FFB600',
  buttonPrimaryHover: '#E6A500',
  buttonPrimaryText: '#FFFFFF',
  buttonSecondary: '#FFFFFF',
  buttonSecondaryHover: '#f5f5f5',
  buttonSecondaryText: '#FFB600',
  logo: '/coj-logo-black.svg',
  logoWhite: '/coj-logo-white.svg',
  connectCardBackground: '/coj-internet-claim-bg.png',
  bannerOverlay: '/banner-overlay.png',
  favicon: '/favicon.svg',
  createdAt: new Date(0).toISOString(),
  updatedAt: new Date(0).toISOString()
};
